### ISSUE TITLE
Unable to play youtube video

### ISSUE THREAD

**Issue by bioblatt** [AlexInCube/AlCoTest#39]
### Who are you? User (who just use bot from discord)/developer/admin (who download all bot stuff to host)?

User, Admin

### Description

Everything worked great a few days ago and now I'm getting the following error:

:error: ERROR
DisTubeError [FFMPEG_EXITED] + 

 + ffmpeg exited with code 8

### Steps To Reproduce

1. !play (youtube link)

### How reliably can you recreate this issue using your steps above?

Always

**Comment by bioblatt** [comment]
Updating the bot in docker to the newest version results in this error:

+ EACCES: permission denied, open '1722454825587-base.js'

**Comment by AlexInCube** [comment]
Fixed in 3.3.1
